# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: main.go
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - linux
    - darwin

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64

  # GOARM to build for when GOARCH is arm.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Default is only 6.
  goarm:
    - 5
    - 6
    - 7

  # GOMIPS and GOMIPS64 to build when GOARCH is mips, mips64, mipsle or mips64le.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Default is empty.
  gomips:
    - hardfloat
    - softfloat
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - id: default
    vendor: Christoph Petrausch
    homepage: https://github.com/hikhvar/exifsorter
    description: sort media files according to the exif meta data. WIP. Heavy WIP.
    license: Apache License 2.0
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
    - "hikhvar/exifsorter:{{ .Tag }}"
